server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: payment-processor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${SPRING_DATASOURCE_USERNAME:payments}
    password: ${SPRING_DATASOURCE_PASSWORD:payments}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/payments}
    username: ${SPRING_R2DBC_USERNAME:payments}
    password: ${SPRING_R2DBC_PASSWORD:payments}

management:
  endpoints:
    web:
      exposure:
        include: health,info
