server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${SPRING_DATASOURCE_USERNAME:payments}
    password: ${SPRING_DATASOURCE_PASSWORD:payments}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/payments}
    username: ${SPRING_R2DBC_USERNAME:payments}
    password: ${SPRING_R2DBC_PASSWORD:payments}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
